project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: "https://kei-torus.github.io" 
  title: "kei-torus's blog"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: sandstone
    date-format: "YYYY-MM-DD"
    css: styles.css

execute:
  freeze: auto