project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: "https://kei-torus.github.io" 
  title: "my-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto